### ISSUE TITLE
misc suggestions

### ISSUE THREAD

**Issue by ianhi** [samwelborn/tomopyui#1]
1. voila

Have you considered also using [voila](https://voila.readthedocs.io/en/stable/using.html) to turn this into an easy to use webpage like thing for users?

2. pre-commit.ci

enabling https://pre-commit.ci/ can be pretty nice for automated style checking and error correction

3. build docs with readthedocs on PRs
instructions here: https://docs.readthedocs.io/en/latest/pull-requests.html

4.
https://github.com/samwelborn/tomopyui/blob/d3527c423290c25507768bbc2029c1bd7b5ecd09/tomopyui/widgets/meta.py#L443

Can you describe the behavior you want here? I'm definitely open to adding new features.

**Comment by ianhi** [comment]
https://github.com/samwelborn/tomopyui/blob/d3527c423290c25507768bbc2029c1bd7b5ecd09/tomopyui/widgets/meta.py#L356-L358

in newer versions of maptlotlib (i think 3.4 and up) you can do:

```python
with plt.ioff():
```

which should be a little bit more robust - also i think i should remove that ioff function now that it is in core mpl

**Comment by ianhi** [comment]
6. you should probably add `install_requires` to setup.cfg - assuming all your deps can be installed with pip then this should make `pip install .` or from pypi much easier.

**Comment by samwelborn** [comment]
Hey @ianhi, thanks for your suggestions.
1. I tried voila, but it does not render any widgets. Could be an issue with my use of the beta version of ipywidgets.
2. I will check it out.
3. Done
4. I tried using your panhandler https://mpl-interactions.readthedocs.io/en/stable/examples/zoom-factory.html and it did not work. It is not high priority right now, but I can check it out in a bit.
5. See [here] (https://github.com/samwelborn/tomopyui/commit/9cb6981e3c27157df649b78c548556bdb2ae7996). Let me know if this is what you meant.
6. Right now my installation instructions necessitate using conda for most everything, and pip just for a few things. Should install both using conda env create -f environment.yml. I think I would like to keep it that way... what are the benefits to having it through pypi as well?

**Comment by samwelborn** [comment]
For 4, I just tried again and it works with the right mouse button. I can update your docs here to reflect that it is your right mouse button.

https://mpl-interactions.readthedocs.io/en/stable/examples/zoom-factory.html#scrolling-and-panning

I may have also not stored it in a variable by accident when I was doing this the first time around.

**Comment by samwelborn** [comment]
Hey @ianhi. Wanted to let you know that I have transitioned away from mpl-interactions in tomopyui. As you are well aware, there are performance issues when dealing with large image datasets with mpl (which is why I think you suggested using napari). While I would love to use napari, I didn't see a good way of keeping the application inside of a notebook, one of my requirements. Since we necessarily have to deal with large datasets on the order of shape (~1024,1024,1024) I found that [bqplot-imagegl](https://github.com/glue-viz/bqplot-image-gl) significantly improves performance and so I have created an image viewer in my app. Try it out, if you'd like.

All this to say thank you for your help, despite not keeping your package in here. You have been very helpful! I still plan on implementing several of the suggestions above when I have some time.

**Comment by ianhi** [comment]
thanks @samwelborn - where can I try it out? also curious your thoughts on https://github.com/ianhi/hyperslicer/issues/1

**Comment by samwelborn** [comment]
you can follow the install instructions here:
https://tomopyui.readthedocs.io/en/latest/install.html

It will work with non-cuda - the cuda part is only for the reconstruction part of the app on the backend.

I don't really have a standalone viewer for it, but it could definitely be developed.

There is a small test-set of data inside the data folder, but you can browse for your own. Should work with tiffs and .npy.

It still lags a bit when viewing very high resolution images, but not as much as mpl. For this reason, I have added a feature where you can downsample the viewer (it will not impact the data going into the reconstruction algorithms for my app).

This is all contained in tomopyui.widgets.plot if you are interested.

I will eventually put up some tutorials on how to use the whole app as it has evolved significantly since my last run-through of the documentation.

**Comment by samwelborn** [comment]
@ianhi Big updates here in recent weeks. Check out tutorial videos here to see the updated UI:
https://tomopyui.readthedocs.io/en/latest/examples.html

I saw that you recently got mpl-interactions on conda-forge. Do you have a link to an instruction page to do that for a purely python package? conda-forge docs are a bit confusing, but maybe you can point me in the right direction :)

**Comment by ianhi** [comment]
> conda-forge docs are a bit confusing, but maybe you can point me in the right direction :)

They are definitely confusing :( but the actual implementation is thankuflly very easy!

1. Fork 
2. Go the `recipes` folder and use [grayskull](https://github.com/conda-incubator/grayskull#usage) to generate the recipe
     - `grayskull pypi tomopyui`
4. Make pull request

**Comment by samwelborn** [comment]
Thanks again for your help - will add to conda forge when I have time. Closing this issue.
