### ISSUE TITLE
Zoom/rectangular selection functionality in import tab viewer

### ISSUE THREAD

**Issue by perlmutter** [samwelborn/tomopyui#5]
I don’t understand the “rectangular selection” button. I can select regions but don't understand the functionality. Can you make its  intended purpose clearer?
Also can you include zoom functionality in place of/in addition to the rectangular selection?
<img width="539" alt="Screen Shot 2022-02-01 at 3 01 48 PM" src="https://user-images.githubusercontent.com/89415472/152065994-d131534c-dcc8-4919-9caa-6aee0945eb06.png">

**Comment by samwelborn** [comment]
I decided to make only one `Plotter` for this tab and the Align and Reconstruct tabs. This is so I don't go through the process of calculating the histogram twice. 

That functionality is meant for the Align and Reconstruct tabs. If you highlight a region and then press the button on the "Altered projections" `Plotter`, that region will show up. This kind of acts like a zoom feature, but actually changes what data you will put into the reconstruction/alignment algorithms. This is important because you may have features in your data you don't want to align to - I have found that my alignment works a lot better/faster if I'm only aligning to a subset of data.

Once I update the documentation for the latest version I can add something about this in.

Maybe could change to copy the whole thing except remove that box in the first view.

**Comment by samwelborn** [comment]
This behavior has been changed significantly in https://github.com/samwelborn/tomopyui/commit/4a1beff8444982a509d79e1a58bddef068219df4 

Removed that `BrushSelector` button from the import tab, as it has no function there. Added a separate class of plotter for the analysis tab. Zooming is now available for all of the plots. 

In addition, the `Altered_Plotter` now has functionality to use a subset of the altered projections for aligning: the selector will choose a subset of the projections to perform the phase correlation on. This not only speeds up the alignment, but can be helpful in alignment by focusing on only one thing in the projection images.
